spring:
  datasource:
    url: ${DB_ENDPOINT}
    username: admin
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

mail:
  address:
    admin: ${ADMIN_MAIL}

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-life-time: 30
  refresh-token-life-time: 120